In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import matplotlib
from matplotlib import rc
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

rc('text', usetex=False)
sns.set_context('paper', font_scale=2.0)
sns.set_style('whitegrid')

In [2]:
raw_data = pd.read_csv('missrate_motivation.csv')
raw_data.columns = ['Benchmark', 'L1TLBMissRate', 'L2TLBMissRate']
raw_data

  Benchmark  L1TLBMissRate  L2TLBMissRate
0        mt      99.000000      96.100061
1        mm      50.753000      39.450000
2        km      65.396655      59.700000
3        st      71.321922      88.540000
4        pr      91.920485      81.090000
5       fir       1.000000      38.000000
6      atax      10.000000      28.000000

In [3]:
stacked_data = raw_data


stacked_data = stacked_data.melt(id_vars=['Benchmark'], value_vars=['L1TLBMissRate', 'L2TLBMissRate'])
stacked_data['Benchmark'] = stacked_data['Benchmark'].str.upper()
stacked_data = stacked_data.sort_values(['Benchmark'])
stacked_data.columns = ['Benchmark', 'Configuration', 'MissRate']
stacked_data = stacked_data.reset_index()
stacked_data

    index Benchmark  Configuration   MissRate
0       6      ATAX  L1TLBMissRate  10.000000
1      13      ATAX  L2TLBMissRate  28.000000
2       5       FIR  L1TLBMissRate   1.000000
3      12       FIR  L2TLBMissRate  38.000000
4       2        KM  L1TLBMissRate  65.396655
5       9        KM  L2TLBMissRate  59.700000
6       1        MM  L1TLBMissRate  50.753000
7       8        MM  L2TLBMissRate  39.450000
8       0        MT  L1TLBMissRate  99.000000
9       7        MT  L2TLBMissRate  96.100061
10      4        PR  L1TLBMissRate  91.920485
11     11        PR  L2TLBMissRate  81.090000
12      3        ST  L1TLBMissRate  71.321922
13     10        ST  L2TLBMissRate  88.540000

In [ ]:
fig, ax = plt.subplots(figsize=(10, 2))
sns.barplot(data=stacked_data, 
            x='Benchmark', hue='Configuration', y='MissRate', 
            palette=['#1A237E', '#E8EAF6'], ec='k',
            ax=ax)
handles, labels = ax.get_legend_handles_labels()
labels=['L1 TLB Miss Rate', 'L2 TLB Miss Rate']
ax.legend(handles, labels, 
          frameon=False,
          fancybox=None, 
          columnspacing=1,
          facecolor=None, edgecolor=None, 
          bbox_to_anchor=(0.5, 1.33), loc=9, ncol=2)
ax.set_ylim(0, 110)
ax.set_yticks([0, 25, 50, 75, 100])
ax.set_ylabel('Miss Rate (%)')
# ax.text(1.25, 1.6, 2.29, 
#         horizontalalignment='center', verticalalignment='center',
#         fontsize=18, bbox=dict(facecolor='white'))
# ax.text(5.25, 1.6, 8.33, 
#         horizontalalignment='center', verticalalignment='center',
#         fontsize=18, bbox=dict(facecolor='white'))
# ax.text(6.25, 1.6, 10.67, 
#         horizontalalignment='center', verticalalignment='center',
#         fontsize=18, bbox=dict(facecolor='white'))
# ax.text(9.25, 1.6, 2.88, 
#         horizontalalignment='center', verticalalignment='center',
#         fontsize=18, bbox=dict(facecolor='white'))

plt.savefig('missrate.pdf', bbox_inches='tight')
plt.savefig('missrate.png', dpi=600, bbox_inches='tight')
plt.show()
plt.close()